In [1]:
# -*- coding: utf-8 -*-

from keras.preprocessing import image     #导入numpy、matplotlib、keras、cv2
import numpy as np
from keras.models import load_model
import cv2
from matplotlib import pyplot as plt


Using TensorFlow backend.
/usr/local/python3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/python3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/python3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/python3/lib/python3.7/site-packages/tensorflow/python/fra

In [2]:
 #加载模型
model = load_model('./model1.h5')    
# 1、模型概括打印
print("模型概括：")
model.summary()
#获取网络层数
print("网络层数：",len(model.layers))
#获取每一层的名称
print("每一层的名称：",model.layers)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
模型概括：
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 28, 28, 16)        160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 7, 7, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1568)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1568)              0    

In [5]:
#获取第零层卷积的权重和偏置
print((model.layers[0]))       #打印第0层网络的名称
layer0 = model.get_layer(index=0) #获取改层
weights0 = layer0.get_weights()   #获取该层的参数W和b

print('=========================================================================')
print("该层权重的的维度：",len(weights0))              #该层权重的的维度：卷积和偏置两项

print('=========================================================================')
print("卷积权重的类型：",type(weights0[0]))           #打印该层的权重的类型
#weights0[0]=weights0[0].astype(np.int16)            #将权重数据类型转为int16


print("卷积核原本的形状：",weights0[0].shape)             #打印该层的权重的形状：3行3列16通道
#转置3x3x1x16=====>16x1x3x3
weights0[0]=weights0[0].transpose(3,2,0,1)
print("卷积核转置后的形状：",weights0[0].shape)             #打印该层的权重的形状：3行3列16通道
#print(weights0[0])             #打印该层的权重
#保存卷积权重到二进制bin文件
weights0[0].tofile("./weight_bin//c1w.bin")
#scio.savemat("./c1w.mat", {'A':weights0[0]})        #c1权重保存到mat文件中

print('=========================================================================')
print("偏置的类型：",type(weights0[1]))           #打印该层的权重的类型
print("偏置的形状：",weights0[1].shape)             #打印该层的权重的形状：3行3列16通道
#转置3x3x1x16=====>16x1x3x3
#weights0[0]=weights0[0].transpose(3,2,0,1)
#print(weights0[1])             #打印该层的权重
weights0[1].tofile("./weight_bin/c1b.bin")

该层权重的的维度： 2
卷积权重的类型： <class 'numpy.ndarray'>
卷积核原本的形状： (3, 3, 1, 16)
卷积核转置后的形状： (16, 1, 3, 3)
偏置的类型： <class 'numpy.ndarray'>
偏置的形状： (16,)


In [6]:
#获取第二层卷积的权重和偏置
layer2 = model.get_layer(index=2) #获取改层
weights2 = layer2.get_weights()   #获取该层的参数W和b
print('=========================================================================')
print("该层权重的的维度：",len(weights2))              #该层权重的的维度：卷积和偏置两项

print('=========================================================================')
print("卷积权重的类型：",type(weights2[0]))           #打印该层的权重的类型
print("卷积核原本的形状：",weights2[0].shape)             #打印该层的权重的形状：3行3列16通道
#转置3x3x16x32=====>32x16x3x3
weights2[0]=weights2[0].transpose(3,2,0,1)
print("卷积核转置后的形状：",weights2[0].shape)             #打印该层的权重的形状：3行3列16通道
print(weights2[0])             #打印该层的权重
#保存卷积权重到二进制bin文件
weights2[0].tofile("./weight_bin//c2w.bin")

print('=========================================================================')
print("偏置的类型：",type(weights2[1]))           #打印该层的权重的类型
print("偏置原本的形状：",weights2[1].shape)             #打印该层的权重的形状：3行3列16通道
print(weights2[1])             #打印该层的权重
weights2[1].tofile("./weight_bin/c2b.bin")

该层权重的的维度： 2
卷积权重的类型： <class 'numpy.ndarray'>
卷积核原本的形状： (3, 3, 16, 32)
卷积核转置后的形状： (32, 16, 3, 3)
[[[[ 0.0955558   0.03922452 -0.25097427]
   [ 0.16857785 -0.02725656 -0.19132093]
   [-0.08175548 -0.10033172 -0.10125921]]

  [[-0.04053079 -0.15918678 -0.0583311 ]
   [ 0.15658604 -0.15012737  0.11678957]
   [-0.05627985  0.08495566 -0.03348925]]

  [[-0.02489801 -0.1430895   0.01578913]
   [-0.05740668  0.17014503  0.12443769]
   [-0.2960375   0.00900051 -0.02006085]]

  ...

  [[ 0.12181476 -0.06771509  0.04779996]
   [ 0.11980715 -0.09162667 -0.06758997]
   [ 0.06297724 -0.03517004 -0.11981961]]

  [[ 0.0995675  -0.04470449  0.06225052]
   [ 0.01354606 -0.06548665  0.00283639]
   [-0.11552183  0.07060124  0.14280926]]

  [[-0.05744582 -0.09331529 -0.13445722]
   [ 0.01491377  0.04618784  0.02726056]
   [-0.06708395 -0.02387498  0.07066359]]]


 [[[ 0.22696668 -0.1819491  -0.16990462]
   [-0.15594646 -0.14613439 -0.03920652]
   [-0.20097618  0.04570065  0.05844005]]

  [[-0.06427912 -0.2

In [7]:
#获取第六层全连接的权重和偏置
layer6= model.get_layer(index=6) #获取改层
weights6 = layer6.get_weights()   #获取该层的参数W和b
print('=========================================================================')
print("第六层全连接的权重维度：",len(weights6))              #该层权重的的维度：权重和偏置两项

print('=========================================================================')
print("矩阵权重的类型：",type(weights6[0]))            #打印该层的权重的类型
print("矩阵权重的总个数：",weights6[0].size)           #权重矩阵的总元素个数
print("矩阵权重原来的形状：",weights6[0].shape)          #权重矩阵的形状：

print("矩阵权重的数据类型：",weights6[0].dtype)          #权重矩阵的形状：
print("矩阵权重原来的行数：",weights6[0].shape[0])          #权重矩阵的形状：
weights6[0]=weights6[0].transpose(1,0)
print("矩阵权重转置后的形状：",weights6[0].shape)          #权重矩阵的形状
print(weights6[0])             #打印该层的权重
#保存卷积权重到二进制bin文件

weights6[0].tofile("./weight_bin//f6w_t.bin")

print('=========================================================================')
print("偏置的类型：",type(weights6[1]))           #打印该层的偏置的类型
print("偏置形状：",weights6[1].shape)             #打印该层的偏置的形状：128x1

print(len(weights6[1]))                          #权重矩阵的列数=输入的全连接层输出的元素个数=128
print(weights6[1])                               #打印该层的偏置
weights6[1].tofile("./weight_bin/f6b.bin")
#weights6[1].tofile('.//fc2_weight.txt', sep=' ',format='%f')

第六层全连接的权重维度： 2
矩阵权重的类型： <class 'numpy.ndarray'>
矩阵权重的总个数： 200704
矩阵权重原来的形状： (1568, 128)
矩阵权重的数据类型： float32
矩阵权重原来的行数： 1568
矩阵权重转置后的形状： (128, 1568)
[[-0.01719927 -0.03823454 -0.01932273 ... -0.04921417  0.05377471
   0.0252989 ]
 [-0.04144293 -0.0072552   0.00199412 ...  0.0326843   0.05900571
  -0.02609367]
 [-0.04186489 -0.03022121 -0.03938598 ... -0.05268966  0.05642483
   0.0467236 ]
 ...
 [ 0.04828049  0.01011903 -0.02746451 ...  0.03128258  0.04817855
   0.0346797 ]
 [-0.02966924 -0.01698747  0.04226634 ...  0.05648492  0.03469853
  -0.01776249]
 [ 0.00390895 -0.03033806  0.04755848 ...  0.04072607 -0.03607173
   0.02111315]]
偏置的类型： <class 'numpy.ndarray'>
偏置形状： (128,)
128
[-0.07601771 -0.06166385 -0.06526529 -0.01232975 -0.05668816 -0.00570615
 -0.07438132 -0.06994422 -0.05234959 -0.03183017 -0.09601714 -0.09900951
 -0.07296367 -0.11196744 -0.11407607 -0.04322184 -0.01594684  0.00234236
 -0.00509172 -0.0559174  -0.01941404 -0.04869796 -0.06330772 -0.09168445
 -0.00638195 -0.08302

In [8]:
#获取第八层全连接的权重和偏置
layer8= model.get_layer(index=8) #获取改层
weights8= layer8.get_weights()   #获取该层的参数W和b
print('=========================================================================')
print(len(weights8))              #该层权重的的维度：权重和偏置两项

print('=========================================================================')
print("矩阵权重的类型：",type(weights8[0]))            #打印该层的权重的类型
print("矩阵权重的总个数：",weights8[0].size)           #权重矩阵的总元素个数 1280
print("矩阵权重的形状：",weights8[0].shape)          #权重矩阵的形状：128x10

weights8[0]=weights8[0].transpose(1,0)
print("矩阵权重转置后的形状：",weights8[0].shape)          #权重矩阵的形状：行3列16通道

print(weights8[0])             #打印该层的权重
#保存卷积权重到二进制bin文件
weights8[0].tofile("./weight_bin//f8w_t.bin")

print('=========================================================================')
print("偏置的类型：",type(weights8[1]))           #打印该层的偏置的类型
print("偏置形状：",weights8[1].shape)             #打印该层的偏置的形状：10x1
print(len(weights8[1]))                          #权重矩阵的列数=输入的全连接层输出的元素个数=128
print(weights8[1])                               #打印该层的偏置
weights8[1].tofile("./weight_bin1/f8b.bin")

2
矩阵权重的类型： <class 'numpy.ndarray'>
矩阵权重的总个数： 1280
矩阵权重的形状： (128, 10)
矩阵权重转置后的形状： (10, 128)
[[ 6.5374054e-02  8.0505675e-03  1.8855231e-02 ...  1.1503628e-01
   1.7478634e-01 -3.4651875e-01]
 [-2.1446282e-01  8.0545016e-02  1.0711244e-01 ... -2.1804452e-02
  -2.1660490e-01 -3.3106476e-01]
 [ 7.2557196e-02  1.1911153e-01 -2.4351113e-01 ... -2.2517715e-02
   1.4211325e-01 -2.5358477e-01]
 ...
 [ 4.9617540e-02  1.3024026e-01  9.0554237e-02 ... -1.7421724e-02
  -2.4326348e-01  1.2257293e-01]
 [-7.0328094e-02  6.0543753e-02 -3.3804965e-01 ...  1.5849833e-01
  -1.7901991e-01  2.8468052e-02]
 [-1.5213530e-01 -7.1544036e-02 -7.9816600e-05 ...  1.8914089e-01
   1.0847200e-01  6.6742025e-02]]
偏置的类型： <class 'numpy.ndarray'>
偏置形状： (10,)
10
[-0.01243159  0.09214074 -0.06272949 -0.02321226 -0.08162592 -0.10588994
 -0.0844419  -0.11360486  0.13890822  0.1077631 ]
